from pathlib import Path


ROOT_DIR = Path(__file__).parent
WINDOW_ICON_PATH = ROOT_DIR / 'icon.png'

#colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 28
TEXT_MARGIN = 15
MINIMUM_WIDTH = 500